version: "3"

#NETWORK
networks:
  my-network:
    driver: bridge

#VOLUMES
volumes:
  dir-site:
    driver_opts:
      device: /d/Webserver
      o: bind

services:
  # CONTAINER PHP
  my-php:
    container_name: php-product
    build:
      dockerfile: Dockerfile
      context: ./php/
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/
    ports:
      - "8080:80"
  # CONTAINER HTTPD
  my-httpd:
    container_name: c-httpd01
    image: "httpd:latest"
    hostname: httpd
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "9999:80"
      - "443:443"
  # container MYSQL
  my-mysql:
    container_name: mysql-product
    image: "mysql:latest"
    hostname: mysql
    restart: always
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_DATABASE=db_site
      - MYSQL_USER=siteuser
      - MYSQL_PASSWORD=sitepass
  #phpmyadmin
  my-phpmyadmin:
    container_name: myadmin-product
    image: "phpmyadmin/phpmyadmin:latest"
    networks: 
      - my-network
    restart: always
    environment: 
      PMA_HOST: my-mysql
    ports: 
      - "8000:80"

    
  